CREATE VIEW CompetitionScreen AS SELECT
	comp_type, comp_id,

	-- COMP NAV --
	(
		SELECT json_group_array(C_child.id) FROM Competition AS C_child
		WHERE C_child.parent_id = C.id
	) AS child_ids,

	(
		SELECT json_group_array(C_sibling.id) FROM Competition AS C_sibling
		WHERE C_sibling.parent_id = C.parent_id
	) AS sibling_ids,

	(	-- Recursive query generated by ChatGPT.
		WITH RECURSIVE Parents(id, parent_id) AS (
			SELECT id, parent_id
			FROM Competition
			WHERE id = C.id

			UNION ALL

			SELECT T.id, T.parent_id
			FROM Competition AS T
			JOIN Parents ON T.id = Parents.parent_id
		)
		SELECT json_group_array(parent_id)
		FROM Parents
		WHERE parent_id IS NOT NULL
	) AS parent_ids,

	(	-- TEAMS --
		SELECT json_group_array(
			json_object(
				'id', team_id,
				'name', full_name,
				'rank', ranking,
				'games', games,
				'regular_wins', regular_wins,
				'ot_wins', ot_wins,
				'draws', draws,
				'ot_losses', ot_losses,
				'regular_losses', regular_losses,
				'goals_scored', goals_scored,
				'goals_conceded', goals_conceded,
				'goal_difference', goal_difference,
				'points', (
					regular_wins * points_for_win +
					ot_wins * points_for_ot_win +
					draws * points_for_draw +
					ot_losses * points_for_ot_loss +
					regular_losses * points_for_loss
				)
			)
		) FROM TeamSeason AS TS
		JOIN Team ON Team.id = TS.team_id
		WHERE TS.season_id = S.id
	) AS teams,

	(	-- KNOCKOUT ROUND --
		SELECT KoP.id FROM KnockoutPair AS KoP
	) AS ko_pair_id

FROM Competition as C
JOIN Season AS S ON C.id = comp_id
LEFT JOIN RoundRobinFormat AS RR ON C.rr_format_id = RR.id
LEFT JOIN KnockoutPair AS KoP ON KoP.season_id = S.id

GROUP BY C.id
ORDER BY S.id DESC;